### ISSUE TITLE
model spec issue when testing associations with Transaction

### ISSUE THREAD

**Issue by lingtran** [lingtran/rails_engine#9]
when testing associations that touch transactions, encounter error:

```
1) Customer association should have many transactions through invoices
     Failure/Error: it { should have_many(:transactions).through(:invoices) }

     NoMethodError:
       undefined method `class_name' for nil:NilClass
       Did you mean?  class_eval
     # /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/association_matcher.rb:1067:in `rescue in class_exists?'
     # /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/association_matcher.rb:1064:in `class_exists?'
     # /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/association_matcher.rb:928:in `matches?'
     # ./spec/models/customer_spec.rb:13:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:42:in `block (3 levels) in <top (required)>'
     # /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:98:in `cleaning'
     # /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:41:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `class_name' for nil:NilClass
     #   Did you mean?  class_eval
     #   /Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_record/association_matchers/model_reflection.rb:16:in `associated_class'

```

```
class Customer < ActiveRecord::Base
  has_many :transactions, through: :invoices
end 
```

```
    it { should have_many(:transactions).through(:invoices) }

```

```
class Merchant < ActiveRecord::Base
 has_many :invoice_items, through: :invoices
end
```

```
     it { should have_many(:invoice_items).through(:invoices) }
```

**Comment by lingtran** [comment]
Resolved via modifying association in Transaction model with ```delegate :customer,  to: :invoice```
